name: (Dev) Test, Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_REPO_NAME: backend-dev
  SERVICE_NAME: coride-backend
  RUN_REGION: asia-east1
  IMAGE_NAME: coride-backend

jobs:
  build-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      IMAGE_URL: ${{ steps.set-release-version-output.outputs.value }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Get short git latest commit hash for version tag
      - name: Set latest commit hash into github env
        id: git
        run: echo "RELEASE_VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      # Define docker image tag
      - name: Set docker image tag into github env
        id: set-release-version-output
        run: echo "DOCKER_IMAGE_URL=$RUN_REGION-docker.pkg.dev/$PROJECT_ID/$GAR_REPO_NAME/$IMAGE_NAME:$RELEASE_VERSION" >> $GITHUB_ENV

      # Setup gcloud CLI
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          token_format: 'access_token'

      - name: Build docker image
        run: docker build -t $DOCKER_IMAGE_URL .

      # set image url as env output
      - id: set-image-url-output
        run: echo "IMAGE_URL=$DOCKER_IMAGE_URL" >> $GITHUB_OUTPUT

      - name: Configure docker authentication
        run: gcloud auth configure-docker -q

      - name: Push docker image to GAR
        run: docker push $DOCKER_IMAGE_URL

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4

      - name: Go Build
        run: go build -v ./...

      - name: Go Test
        run: go test -v ./...

  deploy:
    name: Deploy to Cloud Run
    needs: [build-push, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          token_format: 'access_token'

      # Deploy image to Cloud Run
      - name: Deploy image to Google Cloud Run
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "{{ needs.build-push.outputs.IMAGE_URL }}" \
            --platform "managed" \
            --port 8080 \
            --allow-unauthenticated