name: Unit Test

on:
  pull_request:
    branches:
      - main
      - prod

env:
  POSTGRES_DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.4

      - name: Go Build
        run: go build -v ./...

      - name: Go Test
        run: go test -v ./...
